"use client";
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { getCurrentUser } from "@/lib/auth";
import { useEmployeeByEmail } from "@/lib/firebase/hooks/useEmployees";
import { useEmployeePayslips } from "@/lib/firebase/hooks/usePayslips";
import { FileText, Download, Calendar, Wallet } from "lucide-react";

export default function EmployeePayslipsPage() {
  const [currentUser, setCurrentUser] = useState<any>(null);
  const [employeeId, setEmployeeId] = useState<string | undefined>(undefined);

  useEffect(() => {
    const user = getCurrentUser();
    setCurrentUser(user);
  }, []);

  const { employee, loading: employeeLoading } = useEmployeeByEmail(
    currentUser?.email
  );

  useEffect(() => {
    if (employee?.id) {
      setEmployeeId(employee.id);
    }
  }, [employee]);

  const { data: payslips, loading: payslipsLoading } = useEmployeePayslips(employeeId);

  const formatCurrency = (amount: number) => {
    return `₹ ${amount.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-4xl font-bold tracking-tight text-slate-900">Payslips</h1>
        <p className="mt-2 text-slate-600">View your monthly payslips and download PDF copies.</p>
      </div>

      <Card hover>
        <CardHeader 
          title="Available Payslips" 
          icon={<Wallet className="text-blue-600" size={20} />}
        />
        <CardContent>
          {payslipsLoading || employeeLoading ? (
            <div className="flex items-center justify-center py-12">
              <div className="text-center">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-2"></div>
                <p className="text-sm text-slate-500">Loading payslips...</p>
              </div>
            </div>
          ) : payslips.length === 0 ? (
            <div className="text-center py-12 text-slate-500">
              <FileText size={48} className="mx-auto mb-4 text-slate-300" />
              <p>No payslips available yet.</p>
              <p className="text-sm mt-2">Your payslips will appear here once they are generated by the admin.</p>
            </div>
          ) : (
            <div className="space-y-4">
              {payslips.map((payslip) => (
                <div
                  key={payslip.id}
                  className="rounded-xl border border-slate-200 bg-gradient-to-br from-white to-slate-50/50 p-6 hover:shadow-md transition-all"
                >
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <div className="flex items-center gap-2 mb-2">
                        <Calendar className="text-blue-600" size={20} />
                        <h3 className="text-lg font-semibold text-slate-900">
                          {payslip.monthName || payslip.month}
                        </h3>
                      </div>
                      <div className="flex items-center gap-4 text-sm text-slate-600">
                        <span>
                          <span className="font-medium">Working Days:</span> {payslip.workingDays}
                        </span>
                        <span>
                          <span className="font-medium">Present:</span> {payslip.presentDays}
                        </span>
                        {payslip.leaveDays > 0 && (
                          <span>
                            <span className="font-medium">Leaves:</span> {payslip.leaveDays}
                          </span>
                        )}
                        {payslip.overtimeHours > 0 && (
                          <span>
                            <span className="font-medium">Overtime:</span> {payslip.overtimeHours.toFixed(1)}h
                          </span>
                        )}
                      </div>
                    </div>
                    <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-medium ${
                      payslip.status === 'paid' ? 'bg-green-100 text-green-700' :
                      payslip.status === 'approved' ? 'bg-blue-100 text-blue-700' :
                      payslip.status === 'generated' ? 'bg-amber-100 text-amber-700' :
                      'bg-slate-100 text-slate-700'
                    }`}>
                      {payslip.status}
                    </span>
                  </div>

                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4 pt-4 border-t border-slate-200">
                    <div>
                      <div className="text-xs text-slate-500 mb-1">Basic Salary</div>
                      <div className="text-base font-semibold text-slate-900">
                        {formatCurrency(payslip.basic)}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs text-slate-500 mb-1">Allowances</div>
                      <div className="text-base font-semibold text-green-600">
                        + {formatCurrency(payslip.allowances)}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs text-slate-500 mb-1">Deductions</div>
                      <div className="text-base font-semibold text-red-600">
                        - {formatCurrency(payslip.deductions)}
                      </div>
                    </div>
                    {payslip.overtime > 0 && (
                      <div>
                        <div className="text-xs text-slate-500 mb-1">Overtime</div>
                        <div className="text-base font-semibold text-green-600">
                          + {formatCurrency(payslip.overtime)}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center justify-between pt-4 border-t border-slate-200">
                    <div>
                      <div className="text-xs text-slate-500 mb-1">Net Pay</div>
                      <div className="text-2xl font-bold text-blue-600">
                        {formatCurrency(payslip.netPay)}
                      </div>
                    </div>
                    <Button
                      variant="outline"
                      onClick={() => {
                        // TODO: Implement PDF download
                        alert("PDF download functionality coming soon!");
                      }}
                    >
                      <Download size={16} className="mr-2" />
                      Download PDF
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}


